# Generated by Django 5.2.15 on 2026-08-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_galleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='download_file',
            field=models.FileField(blank=True, null=True, upload_to='album-downloads/'),
        ),
    ]
