# Generated by Django 5.2.15 on 2026-08-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_album_download_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='is_for_sale',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='album',
            name='price_cents',
            field=models.PositiveIntegerField(default=1000),
        ),
    ]
