# Generated by Django 5.2.15 on 2026-08-09 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_album_is_for_sale_album_price_cents'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_session_id', models.CharField(max_length=255, unique=True)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('amount_paid', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='core.album')),
            ],
        ),
    ]
